//! Shell completions and the man page, written from [`super::spec`].
//!
//! Generated from the same table as the parser rather than pulled from a
//! library, which keeps two dependencies and a few hundred kilobytes of
//! binary out of an app whose whole argument is that it is fast and small.
//! The shapes here are plain enough that the table is the hard part, and the
//! table already exists.
//!
//! The package runs the built binary to produce these, so they cannot be
//! generated from a different version of the surface than the one installed.

use super::spec::{Noun, SURFACE};

pub fn script(shell: &str) -> String {
    match shell {
        "zsh" => zsh(),
        "fish" => fish(),
        _ => bash(),
    }
}

fn nouns() -> String {
    SURFACE.iter().map(|n| n.name).collect::<Vec<_>>().join(" ")
}

fn verbs(noun: &Noun) -> String {
    noun.verbs.iter().map(|v| v.name).collect::<Vec<_>>().join(" ")
}

fn bash() -> String {
    let mut out = String::from(
        "# omacharts completion for bash. Generated by `omacharts surface --completions bash`.\n\
         _omacharts() {\n  local cur prev\n  COMPREPLY=()\n  \
         cur=\"${COMP_WORDS[COMP_CWORD]}\"\n  prev=\"${COMP_WORDS[1]}\"\n\n  \
         if [ \"$COMP_CWORD\" -eq 1 ]; then\n    \
         COMPREPLY=( $(compgen -W \"",
    );
    out.push_str(&nouns());
    out.push_str(" help surface --help --version\" -- \"$cur\") )\n    return\n  fi\n\n  case \"$prev\" in\n");
    for noun in SURFACE {
        out.push_str(&format!("    {})\n      COMPREPLY=( $(compgen -W \"{}\" -- \"$cur\") )\n      ;;\n", noun.name, verbs(noun)));
    }
    out.push_str("  esac\n}\ncomplete -F _omacharts omacharts\n");
    out
}

fn zsh() -> String {
    let mut out = String::from(
        "#compdef omacharts\n# Generated by `omacharts surface --completions zsh`.\n\
         _omacharts() {\n  local -a nouns\n  nouns=(\n",
    );
    for noun in SURFACE {
        out.push_str(&format!("    '{}:{}'\n", noun.name, noun.about));
    }
    out.push_str("  )\n  if (( CURRENT == 2 )); then\n    _describe 'command' nouns\n    return\n  fi\n  case \"${words[2]}\" in\n");
    for noun in SURFACE {
        out.push_str(&format!("    {})\n      local -a verbs\n      verbs=(\n", noun.name));
        for verb in noun.verbs {
            out.push_str(&format!("        '{}:{}'\n", verb.name, verb.about));
        }
        out.push_str("      )\n      _describe 'subcommand' verbs\n      ;;\n");
    }
    out.push_str("  esac\n}\n_omacharts \"$@\"\n");
    out
}

fn fish() -> String {
    let mut out =
        String::from("# Generated by `omacharts surface --completions fish`.\n");
    for noun in SURFACE {
        out.push_str(&format!(
            "complete -c omacharts -n __fish_use_subcommand -a {} -d '{}'\n",
            noun.name,
            noun.about.replace('\'', "")
        ));
        for verb in noun.verbs {
            out.push_str(&format!(
                "complete -c omacharts -n '__fish_seen_subcommand_from {}' -a {} -d '{}'\n",
                noun.name,
                verb.name,
                verb.about.replace('\'', "")
            ));
        }
    }
    out
}

/// The man page, in roff.
pub fn man() -> String {
    let mut out = format!(
        ".TH OMACHARTS 1 \"\" \"omacharts {}\" \"User Commands\"\n\
         .SH NAME\nomacharts \\- fast, beautiful market charts for the Linux desktop\n\
         .SH SYNOPSIS\n.B omacharts\n[\\fISYMBOL\\fR]\n.br\n.B omacharts\n\
         \\fICOMMAND\\fR \\fISUBCOMMAND\\fR [\\fIARGUMENTS\\fR]\n\
         .SH DESCRIPTION\nEverything the window can do can be done from here. A command\n\
         changing anything takes effect in a window that is already open,\n\
         straight away.\n.PP\nWith nothing running, the same commands work against the stored\n\
         data, so this is usable over ssh and out of a script.\n",
        env!("CARGO_PKG_VERSION")
    );
    out.push_str(".SH COMMANDS\n");
    for noun in SURFACE {
        out.push_str(&format!(".SS {}\n{}\n", noun.name, noun.about));
        for verb in noun.verbs {
            out.push_str(&format!(
                ".TP\n.B omacharts {} {}\n{}\n.br\nExample: \\fB{}\\fR\n",
                noun.name, verb.name, verb.about, verb.example
            ));
        }
    }
    out.push_str(".SH EXIT STATUS\n");
    for (code, meaning) in super::EXIT_CODES {
        out.push_str(&format!(".TP\n.B {code}\n{meaning}\n"));
    }
    out.push_str(
        ".SH SEE ALSO\nThe full command surface as JSON, for anything driving this from a\n\
         script:\n.PP\n.B omacharts surface --json\n",
    );
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A completion naming a command the parser does not have sends people
    /// down a dead end, which is worse than no completion at all.
    #[test]
    fn every_shell_offers_every_command() {
        for shell in ["bash", "zsh", "fish"] {
            let text = script(shell);
            for noun in SURFACE {
                assert!(text.contains(noun.name), "{shell} is missing {}", noun.name);
                for verb in noun.verbs {
                    assert!(
                        text.contains(verb.name),
                        "{shell} is missing {} {}",
                        noun.name,
                        verb.name
                    );
                }
            }
        }
    }

    #[test]
    fn the_man_page_documents_every_command_and_every_exit_code() {
        let page = man();
        for noun in SURFACE {
            for verb in noun.verbs {
                assert!(
                    page.contains(&format!("omacharts {} {}", noun.name, verb.name)),
                    "the man page is missing {} {}",
                    noun.name,
                    verb.name
                );
            }
        }
        for (code, _) in super::super::EXIT_CODES {
            assert!(page.contains(&format!(".B {code}\n")), "no exit status {code}");
        }
    }
}
