#!/usr/bin/env python3
"""Build the generated half of the symbol inventory.

The curated half lives in crates/omacharts-engine/src/seed.tsv and is written
by hand: it carries the tier weights that make GC mean gold futures, the
session origins that make a 4H bar bucket correctly, and every futures root,
currency pair and crypto, none of which appear in any listings feed.

This writes the other half — every US-listed equity and ETF — from Nasdaq
Trader's daily files. They give a ticker and a name and nothing else, so
everything here lands at tier 2, below anything curated, and the merge at load
time lets a curated row win wherever both have a symbol.

Run: tools/build_listings.py > crates/omacharts-engine/src/listings.tsv
"""

import re
import sys
import urllib.request

NASDAQ = "https://www.nasdaqtrader.com/dynamic/SymDir/nasdaqlisted.txt"
OTHER = "https://www.nasdaqtrader.com/dynamic/SymDir/otherlisted.txt"

# otherlisted.txt names the venue with a single letter. A code not in here is
# written as unknown rather than printed raw: a column saying "F" tells nobody
# anything, and guessing which venue it is would be worse.
VENUES = {
    "N": "NYSE",
    "P": "NYSE Arca",
    "Z": "Cboe BZX",
    "A": "NYSE American",
    "V": "IEX",
}

# Instruments whose name says they are not something anyone charts: the paper
# around a listing rather than the listing. Dropping them is 14% of the file.
NOISE = re.compile(
    r"\b(warrant|warrants|right|rights|unit|units|preferred|depositary|"
    r"debenture|notes due|subordinated)\b|%\s*series",
    re.IGNORECASE,
)


def fetch(url: str) -> list[str]:
    request = urllib.request.Request(url, headers={"User-Agent": "omacharts-listings"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return response.read().decode("utf-8", "replace").splitlines()


def rows(
    lines: list[str],
    symbol_at: int,
    name_at: int,
    etf_at: int,
    test_at: int,
    venue_at: int | None,
):
    for line in lines[1:]:
        fields = line.split("|")
        # The last line of both files is a timestamp, not a listing.
        if len(fields) <= max(symbol_at, name_at, etf_at, test_at):
            continue
        symbol, name = fields[symbol_at].strip(), fields[name_at].strip()
        if not symbol or not name or fields[test_at].strip() == "Y":
            continue
        # Over five characters is a test issue or a non-common class in
        # Nasdaq's fifth-letter scheme, neither of which is a chart.
        if len(symbol) > 5 or NOISE.search(name):
            continue
        if not re.fullmatch(r"[A-Z][A-Z0-9.\-]*", symbol):
            continue
        kind = "etf" if fields[etf_at].strip() == "Y" else "equity"
        code = fields[venue_at].strip() if venue_at is not None else ""
        venue = VENUES.get(code, "-") if code else "NASDAQ"
        # One trailing qualifier is enough; the rest is boilerplate nobody
        # reads in a picker a few characters wide.
        name = re.split(r"\s+-\s+", name)[0].strip()
        name = re.sub(r"\s+(Common Stock|Ordinary Shares?|Class [A-Z])$", "", name).strip()
        yield kind, symbol, name or symbol, venue


def main() -> int:
    seen: dict[str, tuple[str, str, str, str]] = {}
    for url, sym, name, etf, test, venue in (
        (NASDAQ, 0, 1, 6, 3, None),
        (OTHER, 0, 1, 4, 6, 2),
    ):
        for row in rows(fetch(url), sym, name, etf, test, venue):
            seen.setdefault(row[1], row)

    print(
        "# kind\tsymbol\tname\tsuffix\tcurrency\ttier\tsession_origin"
        "\tyahoo_override\texchange"
    )
    print("# Generated by tools/build_listings.py from Nasdaq Trader's daily")
    print("# files. Do not edit: the curated inventory is seed.tsv, and a symbol")
    print("# in both takes the curated row. Everything here is tier 2.")
    for kind, symbol, label, venue in sorted(seen.values(), key=lambda r: r[1]):
        print(f"{kind}\t{symbol}\t{label}\t-\tUSD\t2\t0\t-\t{venue}")
    print(f"# {len(seen)} listings", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
